@startuml Data services
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

skinparam BackgroundColor #00000000

System_Boundary(ppud, "New Data Services") {
  Container(ppudAPI, "Parole API", "node.js / Java", "Exposes data concerned with parole.")
  SystemDb_Ext(legacyDB, "Legacy PPUD DB", "MSSQL")
  ContainerDb(ppudDB, "Parole DB", "RDS")
  ContainerDb(docStorage, "Document Store", "S3 Bucket")
  Rel(ppudAPI, legacyDB, "Fetches legacy data on demand from")
  Rel(ppudAPI, ppudDB, "Writes data to and fetches data from")
  Rel(ppudAPI, docStorage, "Manages files in")
}

@enduml
