@startuml
left to right direction
!include ../legacy_db/style_minimal.puml

!include ../legacy_db/common.puml
!include ../legacy_db/registers.puml
!include ../legacy_db/organisations.puml

!include ../legacy_db/moj/index.puml
!include ../legacy_db/offenders/index.puml
!include ../legacy_db/documents/index.puml

' Remove things that aren't core
remove application.wam
remove mhcs.detention_authorities
remove ppcs.directions
remove mhcs.leave_requests
remove ppcs.reviews
remove ppo.contacts
remove mhcs.movements
remove ppcs.panels
remove ppcs.hearings
remove unknown
@enduml
