@startuml
!include ../style.puml

namespace ppcs $MajorPackage {

  !include reviews.puml
  !include releases.puml
  !include recalls.puml
  !include milestones.puml
  !include deferrals.puml
  !include directions.puml
  !include fno_transfers.puml
  !include hearings.puml
  !include minutes.puml
  !include contacts.puml

}

@enduml
