@startuml
!include ../style.puml

namespace downloads $MinorPackage {

	class CASEWORKER_DOCUMENT_DOWNLOADS {
		* ID : int
		-- Foreign Keys --
		CASEWORKER : int
		DISCLOSURE : int
		---
		DATE_CREATED : datetime
		CASEWORKER_IS_BATCH : bit
	}

	class DOCUMENT_DOWNLOAD_BATCH {
		* ID : int
		-- Foreign Keys --
		CASEWORKER : int
		---
		REQUEST_DATE : datetime
	}

	class DOCUMENT_UNIT_DOWNLOAD {
		* ID : int
		-- Foreign Keys --
		* UNIT : int
		DOCUMENT : int
		DOSSIER : int
		---
		DATE_OF_REQUEST : datetime
		UNIT_IS_BATCH : bit
	}


  class PANEL_MEMBER_DOWNLOAD {
    * ID : int
    -- Foreign Keys --
    * PANEL_MEMBER : int
    * HEARING : int
    ---
    DOSSIER_DOWNLOAD_DATE : datetime
    DOSSIER_DOWNLOAD_VERSION : int
    TIMETABLE_DOWNLOAD_DATE : datetime
  }

	ppcs.panels.PANEL_MEMBER ||--o{ PANEL_MEMBER_DOWNLOAD
	ppcs.hearings.HEARING ||--o{ PANEL_MEMBER_DOWNLOAD

  CASEWORKER_DOCUMENT_DOWNLOADS }o-u-o| moj.caseworkers.CASEWORKER

  DOCUMENT_DOWNLOAD_BATCH }o-u-o| moj.caseworkers.CASEWORKER

  DOCUMENT_UNIT_DOWNLOAD }o-u-o| unknown.UNIT
  DOCUMENT_UNIT_DOWNLOAD }o-u-o| documents.DOCUMENTS
  DOCUMENT_UNIT_DOWNLOAD }o-u-o| documents.dossiers.DOSSIER

}
@enduml
