@startuml
!include ../style.puml

namespace minutes $MinorPackage {

	class MINUTES {
		* ID : int
		-- Foreign Keys --
		OFFENDER : int
		DETENTION_AUTHORITY : int
		COURT_APPEARANCE : int
		RELEASE : int
		REVIEW : int
		MOVEMENT : int
		LEAVE_REQUEST : int
		FAILURE_IN_OPEN : int
		CPPC : int
		SFO : int
		RECALL : int
		CONTACT_LOG : int
		DIRECTION : int
		SENTENCE : int
		---
		* PERSONAL_DETAILS : bit
		* OFFENCE_DETAILS : bit
		* SENTENCE_DETAILS : bit
		MINUTES : text
		-- Foreign Keys --
		---
		* CHANGED : timestamp
	}

	class MINUTES_BACKUP {
		* ID : int
		-- Foreign Keys --
		---
		MINUTES : text
	}

	class MINUTES_XSLT {
		-- Foreign Keys --
		---
	*	TRANSFORM_XML : xml
	}

	MINUTES }o-u-o| offenders.OFFENDER
	MINUTES }o-u-o| offenders.sentences.SENTENCE
	MINUTES }o-u-o| offenders.sfo.SFO
	MINUTES }o-u-o| offenders.cppc.CPPC_CASE

	MINUTES }o-u-o| ppcs.directions.DIRECTION


	MINUTES }o-u-o| mhcs.movements.MOVEMENT
	MINUTES }o-u-o| mhcs.leave_requests.LEAVE_REQUEST
	MINUTES }o-u-o| mhcs.detention_authorities.DETENTION_AUTHORITY

	MINUTES }o-u-o| ppo.contacts.CONTACT


}

@enduml
