@startuml
!include ../style.puml

namespace ppcs $MajorPackage {

  !include hearings.puml
  !include panels.puml
	!include panel_members.puml
	!include member_fees.puml
	!include member_development.puml
  !include attendees.puml
  !include deferrals.puml
  ' !include milestones.puml
}

@enduml
