@startuml
!include ../style.puml

namespace probation_reports $MinorPackage {

  class PROBATION_REPORT {
    * PROBATION_REPORT_ID : int
    -- Foreign Keys --
    * OFFENDER_ID : int
    * CASEWORKER_ID : int
    ACTION_TYPE : int
    REPORT_TYPE : int
    OWNING_TEAM : int
    PRIORITY : int
    ---
    DELIVERY_TARGET : datetime
    DELIVERY_ACTUAL : datetime
    REPLY_TARGET : datetime
    REPLY_ACTUAL : datetime
    COMMENTS : varchar(255)
    ACTION_TARGET : datetime
    ACTION_ACTUAL : datetime
    DOCUMENT_TITLE : varchar(255)
    DOCUMENT_LOCATION : varchar(512)
    DOCUMENT_SIZE : int
    POST_RELEASE : int
    -- Audit --
    * CHANGED : timestamp
    DELETED : datetime
  }

	class PROB_REPORT_TYPE <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		* DELAY : int
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class PR_ACTION_TYPE <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

  PROBATION_REPORT }o-u-|| offenders.OFFENDER
  PROBATION_REPORT }o-u-|| moj.caseworkers.CASEWORKER
  PROBATION_REPORT }o-u-o| common.PRIORITY
  PROBATION_REPORT }o-u-o| moj.caseworkers.CASEWORKER_TEAM
  PROBATION_REPORT }o--o| PROB_REPORT_TYPE
  PROBATION_REPORT }o--o| PR_ACTION_TYPE
}

@enduml
