@startuml
left to right direction
!include ../legacy_db/style_minimal.puml

!include ../legacy_db/ppcs/index_panels.puml

' hide references to core for clarity
remove offenders.risk_assessments
remove offenders.sentences
remove moj
remove registers
remove mhcs.detention_authorities
remove common
remove wam_messages
remove unknown
@enduml
