@startuml Core Data
left to right direction
!include ../style_minimal.puml

!include ../common.puml
!include ../registers.puml
!include ../organisations.puml

!include ../moj/index.puml
!include ../offenders/index.puml
!include ../documents/index.puml

' Remove things that aren't core
remove application.wam
remove mhcs.detention_authorities
remove ppcs.directions
remove mhcs.leave_requests
remove ppcs.reviews
remove ppo.contacts
remove mhcs.movements
remove ppcs.panels
remove ppcs.hearings
remove unknown
@enduml
