@startuml
left to right direction
!include ../style_minimal.puml

!include ../common.puml
!include ../moj/index.puml
!include ../offenders/index.puml
!include ../mhcs/index.puml
!include ../movement.puml

' Hide some tables we probably don't need in this slice
remove organisations
remove application.wam
remove courts
@enduml
