@startuml Ombuds
left to right direction
!include ../style_minimal.puml

!include ../ppo/index.puml

' hide references to core for clarity
remove offenders.sentences
remove offenders.cppc
remove ppcs.reviews
remove common
@enduml
