@startuml
!include ../style_minimal.puml

!include ../common.puml
!include ../moj/index.puml
!include ../offenders/index.puml
!include ../ppcs/index.puml

' Hide some tables we probably don't need in this slice
remove mhcs.detention_authorities
remove organisations
remove hearings
remove panels.fees
remove common
remove application.wam
remove wam_messages

remove ppcs.milestones

remove ppcs.reviews.MILESTONE_TEMPLATE
remove ppcs.reviews.MILESTONE_TEMPLATE_EMAIL
remove ppcs.reviews.REVIEW_MILESTONE_DATE
remove ppcs.reviews.REVIEW_MILESTONE_DATE_EMAIL
remove ppcs.reviews.REVIEW_TYPE_MILESTONE
remove ppcs.reviews.REVIEW_ASSESSOR_HISTORY
remove ppcs.reviews.REVIEW_ADHOC_PROCESS_LOG
remove ppcs.reviews.LATE_REASON
remove ppcs.reviews.REVIEW_COLOUR_HISTORY
remove ppcs.reviews.SOLICITOR_STATUS

remove ppcs.recalls.RECALL_MILESTONE_TEMPLATE
remove ppcs.recalls.RECALL_MILESTONE_DATE
remove ppcs.recalls.RTC_NOTIF_METHOD

remove offenders.sentences.PPO_SENTENCE_TYPE
remove offenders.sentences.TRANSCRIPT_WRITER
remove offenders.OFFENDER_VLO

remove moj.establishments.STAFF
remove moj.establishments.STAFF_GRADE
remove moj.establishments.STAFF_ESTABLISHMENT
remove moj.establishments.ESTABLISHMENT_TEAM

remove moj.caseworkers.CASEWORKER_TEAM_REPORT_CATEGORY
remove moj.caseworkers.Report_Category
remove moj.caseworkers.GRADE
remove moj.caseworkers.CLIENT_SYSTEM
remove moj.caseworkers.CASEWORKER_TEAM
remove moj.caseworkers.UNIT

remove registers.TRIBUNAL_OFFICE
remove registers.CORONER_AREA

@enduml
