@startuml Release and Recall
left to right direction
!include ../style_minimal.puml

!include ../ppcs/index.puml
!include ../documents/index.puml

' panels and hearings are in another diagram
remove ppcs.panels
remove ppcs.panels.fees
remove ppcs.hearings
remove ppcs.milestones

' hide references to core for clarity
remove offenders.risk_assessments
remove offenders.sentences
remove moj
remove moj.establishments
remove registers
remove organisations
remove mhcs.detention_authorities
remove common
remove unknown
@enduml
