@startuml Release and Recall
left to right direction
!include ../style_minimal.puml

!include ../ppcs/index_parole.puml

' panels and hearings are in another diagram
remove ppcs.panels
remove ppcs.fees
remove ppcs.hearings
remove ppcs.milestones
remove ppcs.probation_reports

' hide references to core for clarity
remove offenders.risk_assessments
remove offenders.sentences
remove moj
remove moj.establishments
remove registers
remove organisations
remove mhcs.detention_authorities
remove common
remove wam_messages
remove unknown
@enduml
