@startuml
!include ../style.puml

namespace moj $MajorPackage {

  class PROBATION_SERVICE {
    * ID : int
    -- Foreign Keys --
    NOM_REGION : int
    CASEWORKER_TEAM : int
    OWNING_CASEWORKER : int
    ---
    * DESCRIPTION : varchar(50)
    -- Visibility --
    SHOW_TO_UNIT : int
    -- Audit --
    UPDATED_BY : int
    UPDATED_DATE : datetime
    CREATED_BY : int
    CREATED_DATE : datetime
    DELETED : datetime
    DELETED_BY : int
  }

  class MAPPA_LEVEL <<LookupTable>> {
    * ID : int
    ---
    * Description : varchar(50)
    MESSAGE : varchar(100)
    -- Visibility --
    SHOW_TO_UNIT : int
    -- Audit --
    DELETED : datetime
    LOV_DELETED_BY : int
    LOV_UPDATED_BY : int
    LOV_UPDATED_DATE : datetime
    LOV_CREATED_BY : int
    LOV_CREATED_DATE : datetime
  }
  class MAPPA_CATEGORY <<LookupTable>> {
    * ID : int
    ---
    * Description : varchar(50)
    -- Visibility --
    SHOW_TO_UNIT : int
    -- Audit --
    DELETED : datetime
    LOV_DELETED_BY : int
    LOV_UPDATED_BY : int
    LOV_UPDATED_DATE : datetime
    LOV_CREATED_BY : int
    LOV_CREATED_DATE : datetime
  }

  !include caseworkers.puml
  !include establishments.puml

  PROBATION_SERVICE }o-u-o| moj.caseworkers.CASEWORKER
  PROBATION_SERVICE }o-u-o| moj.caseworkers.CASEWORKER_TEAM
  PROBATION_SERVICE }o-u-o| registers.NOMS_REGION

}


@enduml
