@startuml
!include ../style.puml

namespace complaints $MinorPackage {
	class COMPLAINT_CATEGORY <<LookupTable>> {
		* ID : int
		-- Foreign Keys --
		---
		* DESCRIPTION : varchar(50)
		COMPLEXITY_ID : int
		* SHOW_PROPERTY : bit
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class COMPLAINT_DATES <<LookupTable>> {
		* ID : int
		-- Foreign Keys --
		---
		* DESCRIPTION : varchar(50)
		DATE_FIELD : varchar(100)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class COMPLAINT_LINK <<JoinTable>> {
		* id : int
		-- Foreign Keys --
		* COMPLAINT_ID1 int
		* COMPLAINT_ID2 int
		-- Audit --
		DATE_CREATED : date
	* CREATED_BY int
	}


	class COMPLAINT_STATUS_PATHS <<JoinTable>> {
		* ID : int
		-- Foreign Keys --
		* FROM_STATUS_ID : int
		* TO_STATUS_ID : int
		---
		* DESCRIPTION : varchar(100)
		MANDATORY_FIELDS : varchar(200)
		-- Audit --
		DELETED : datetime
	}

	class COMPLAINT_SUB_CATEGORY <<LookupTable>> {
		* ID : int
		-- Foreign Keys --
		COMPLAINT_CATEGORY_ID : int
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class COMPLAINTS {
		* COMPLAINT_ID : int
		-- Foreign Keys --
		* OFFENDER_ID : int
		SENTENCE_ID : int
		* ESTABLISHMENT_ID : int
		* COMPLAINT_CATEGORY_ID : int
		* COMPLAINT_SUB_CATEGORY_ID : int
		COMPLAINT_OUTCOME_ID : int
		* COMPLEXITY_ID : int
		* COMPLAINT_STATUS_ID : int
		SECOND_ESTABLISHMENT_ID : int
		COMPLAINT_SENTENCE_TYPE_ID : int
		CASEASSESSOR_ID : int
		ASSESSMENT_TEAM_MANAGER_ID : int
		CASE_INVESTIGATOR_ID : int
		INVESTIGATOR_TEAM_MANAGER_ID : int
		* REVIEW_ID : int
		* EQUALITIES_ID : int
		* INELIGIBLE_ID : int
		---
		* PRESS_ATTENTION : bit
		* MP_INTEREST : bit
		* HL_INTEREST : bit
		* DESCRIPTION : varchar(200)
		* COMPLAINT_DATE : datetime
		INCIDENT_DATE : datetime
		DETAILS : text
		CHARGE_NUMBER : varchar(20)
		PROPERTY_DETAILS : text
		* PROPERTY_ELECTRONICS : bit
		* PROPERTY_CLOTHING : bit
		* PROPERTY_PERSONAL_EFFECTS : bit
		* PROPERTY_VALUABLES : bit
		* PROPERTY_OTHER : bit
		* HISTORY_SELF_HARM : bit
		* HISTORY_SUICIDE : bit
		* ON_ACCT : bit
		* HISTORY_ACCT : bit
		* DATE_CREATED : datetime
		* CREATED_BY : int
		SELFHARM_DETAILS : text
		SECOND_ESTABLISHMENT_REASON : varchar(200)
		* PROPERTY_LEGAL_PAPERWORK : bit
		DATE_INELIGIBLE : datetime
		DATE_ALLOCATED : datetime
		DATE_COMPLETE : datetime
		DATE_CLOSED : datetime
		-- Foreign Keys --
		---
		* CHANGED : timestamp
		RECORD_LAST_SAVED_BY : int
		DELETED : datetime
		DELETED_BY : int
	}

	class COMPLAINTS_DEFERRAL <<JoinTable>> {
		* COMPLAINT_DEFERRAL_ID : int
		-- Foreign Keys --
		COMPLAINT_ID : int
		COMPLAINT_DEFERRAL_REASON_ID : int
		* DEFERRAL_PERIOD : int
		AUTHORISED_BY : int
		---
		* CREATED_BY : int
		* DATE_CREATED : datetime
		DATE_AUTHORISED : datetime
		REASON : varchar(200)
		FII_ID : int
	}


	class COMPLAINT_DEFERRAL_REASON <<LookupTable>> {
		* ID : int
		---
		DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class COMPLAINT_INELIGIBLE_REASON <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class COMPLAINT_OUTCOME <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class COMPLAINT_SENTENCE_TYPE <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class COMPLAINT_STATUS <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class EQUALITIES <<LookupTable>> {
		* ID : int
		-- Foreign Keys --
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	COMPLAINTS }o-u-|| offenders.OFFENDER
	COMPLAINTS }o-u-o| offenders.sentences.SENTENCE
	COMPLAINTS }o-u-|{ moj.ESTABLISHMENT
	COMPLAINTS }o--|| COMPLAINT_CATEGORY
	COMPLAINTS }o--|| COMPLAINT_SUB_CATEGORY
	COMPLAINTS }o--o| COMPLAINT_OUTCOME
	COMPLAINTS }o--o| COMPLAINT_STATUS
	COMPLAINTS }o--o| COMPLAINT_SENTENCE_TYPE
	COMPLAINTS }o--o| COMPLAINT_INELIGIBLE_REASON
	COMPLAINTS }o--o| EQUALITIES
	COMPLAINTS ||-o{ COMPLAINTS_DEFERRAL

	COMPLAINT_STATUS }|-u-o{ COMPLAINT_STATUS_PATHS

	COMPLAINTS_DEFERRAL }o-|| COMPLAINT_DEFERRAL_REASON

	COMPLAINT_LINK }o-|{ COMPLAINTS

	!include fatal_incident_investigations.puml

}

@enduml
