@startuml
!include ../style.puml

namespace ppo $MajorPackage {

	!include complaints.puml
	!include fatal_incident_investigations.puml
	!include issues.puml
	!include recommendations.puml

}

@enduml
