@startuml
!include style.puml

namespace actions $MinorPackage {

	class ACTION {
		* ACTION_ID : int
		-- Foreign Keys --
		* PARENT_SFO_ID : int
		---
		ACTION_NO : int
		RECOMMENDED_ACTION : varchar(5000)
		ROLE_RESPONSIBLE : varchar(255)
		ACTION_TARGET : datetime
		ACTION_ACTUAL : datetime
		OTHER_FIELD : varchar(50)
		EFFECTIVENESS_MEASURE : varchar(512)
		COMMENTS : varchar(255)
		LEARNING_POINT : varchar(255)
	}

}

@enduml
