@startuml
!include style.puml

namespace common $MinorPackage {

  class PRIORITY <<LookupTable>> {
    * ID : int
    ---
    DESCRIPTION : varchar(50)
    -- Visibility --
    SHOW_TO_UNIT : int
    -- Audit --
    DELETED : datetime
    LOV_DELETED_BY : int
    LOV_UPDATED_BY : int
    LOV_UPDATED_DATE : datetime
    LOV_CREATED_BY : int
    LOV_CREATED_DATE : datetime
  }

  class TITLE <<LookupTable>> {
    * ID : int
    ---
    DESCRIPTION : varchar(50)
    -- Visibility --
    SHOW_TO_UNIT : int
    -- Audit --
    DELETED : datetime
    LOV_DELETED_BY : int
    LOV_UPDATED_BY : int
    LOV_UPDATED_DATE : datetime
    LOV_CREATED_BY : int
    LOV_CREATED_DATE : datetime
  }

	class AGE_RANGE <<LookupTable>> {
		* ID : int
		---
		* Description : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

}

@enduml
