@startuml
!include style_minimal.puml

!include common.puml
!include registers.puml
!include application/index.puml
!include moj/index.puml
!include offenders/index.puml

!include documents/index.puml
!include mhcs/index.puml
!include ppcs/index.puml
!include ppo/index.puml

!include panels/index.puml
!include organisations.puml
!include probation.puml
!include courts.puml
!include fno_transfers.puml
!include serious_further_offences.puml
!include cppc_cases.puml
!include risk_assessments.puml
!include wam_messages.puml
!include attendees.puml
!include hearings.puml
!include actions.puml
!include contacts.puml
!include deferrals.puml
!include victims.puml

'!include unknown.puml
@enduml
