@startuml
!include style_minimal.puml

!include common.puml
!include registers.puml
!include organisations.puml

!include application/index.puml

!include moj/index.puml
!include offenders/index.puml

!include documents/index.puml
!include notifications/index.puml

!include mhcs/index.puml
!include ppcs/index.puml
!include ppo/index.puml

!include panels/index.puml

!include reporting/index.puml

' !include unknown.puml
@enduml
