@startuml
!include style.puml

namespace templates $MinorPackage {


	class TEMPLATE_QUESTION {
		* TEMPLATE_QUESTION_ID : int
		-- Foreign Keys --
		---
		* QUESTION_GROUP : int
		NUMBER : int
		QUESTION_TEXT : varchar(255)
		* QUESTION_TYPE : int
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		DELETED_BY : int
		UPDATED_BY : int
		UPDATED_DATE : datetime
		CREATED_BY : int
		CREATED_DATE : datetime
	}

	class STAGE_3_QUESTION {
		* S3Q_ID int
		* SFO_ID : int
		* TEMPLATE_QUESTION_ID : int
		QUESTION_GROUP : int
		NUMBER : int
		QUESTION_TEXT : varchar(255)
		* ANSWER : int
		* LEARNING_POINT_FLAG : bit
		* GOOD_PRACTICE_FLAG : bit
		QUESTION_TYPE : int
		-- Audit --
		DELETED : datetime
	}

	class QUESTION_GROUP <<LookupTable>> {
		* ID : int
		---
		DESCRIPTION : varchar(50)
		EXTENDED_DESCRIPTION : varchar(100)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class QUESTION_TYPE <<LookupTable>> {
		* ID : int
		---
		DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class NUMBERS {
		* N : int
	}

	class TEMPLATE_TASK_ACTIONS {
		* TEMPLATE_TASK_ID : int
		-- Foreign Keys --
		---
		* TEMPLATE_ID : int
		* DOSSIER_ACTION_ID : int
		* TEMPLATE_MILESTONE_TASK_ID : int
	}

	class EMAIL_TEMPLATES {
		* ID : int
		-- Foreign Keys --
		---
		DESCRIPTION : varchar(50)
		TEMPLATE : text
	}




}

@enduml
