@startuml
!include style.puml

namespace unknown $MinorPackage {

	class YES_NO <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class ddtemp <<TempTable>> {
		docid : int
		scandate : datetime
	}

	class TEMP_SUMMARY <<TempTable>> {
		* MNP : varchar(50)
		comments : text
	}

	class DATES {
		* DATE : datetime
		---
		* WEEKEND : bit
		* BANK_HOLIDAY : bit
	}

	class BANK_HOLIDAY <<LookupTable>> {
		* BANK_HOLIDAY : datetime
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		CREATED_BY : int
		CREATED_DATE : datetime
		UPDATED_BY : int
		UPDATED_DATE : datetime
		DELETED_BY : int
	}

	class tmp_rhmarch <<TempTable>> {
		prison_number : varchar(50)
		offender_Id : int
	}

	class tmpdocs <<TempTable>> {
		filename : varchar(100)
	}

	class tmp_mnp <<TempTable>> {
		mnp : varchar(20)
		offender_id : int
		pages : int
		document_id : int
		page_from : int
		page_to : int
	}

	class tmp_prisno <<TempTable>> {
		* prison_number : varchar(10)
		-- Foreign Keys --
		---
		oid : int
		rid : int
	}

	class DDDUPPAGES {
		DOCID : int
		---
		PAGE_NO : int
		TIMES : int
	}


	class TASK_TYPE <<LookupTable>> {
		* ID : int
		---
		DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class TEST_RECORDER {
		* ID : int
		-- Foreign Keys --
		---
		TITLE : varchar(1000)
		STATUS : varchar(100)
		TESTDATE : datetime
	}

}

@enduml
