@startuml
!include style.puml

namespace victims $MinorPackage {

	class VICTIM {
		* VICTIM_ID : int
		-- Foreign Keys --
		* PARENT_SFO_ID : int
		---
		* GENDER : varchar(50)
		* AGE : int
		* KNOWN_TO_OFFENDER_FLAG : bit
		* REVICTIMISATION_FLAG : bit
		* TGT_ETHNICITY_FLAG : bit
		* TGT_SEXUALITY_FLAG : bit
		* TGT_GENDER_FLAG : bit
		* TGT_DISABILITY_FLAG : bit
		* TGT_BELIEF_FLAG : bit
		* TGT_AGE_FLAG : bit
		* TGT_CLASS_FLAG : bit
		* TGT_SPEC_VULN_FLAG : bit
		* TGT_OTHER_FLAG : bit
		COMMENTS : varchar(255)
		-- Audit --
		CHANGED : timestamp
	}

}

@enduml
