@startuml
!include ../style.puml

namespace panels $MajorPackage {

	class PANEL {
		* ID : int
		-- Foreign Keys --
		* PANEL_STATUS : int
		* PANEL_TYPE : int
		HOSTING_ESTABLISHMENT : int
		---
		START_DATE : datetime
		END_DATE : datetime
		ESTABLISHMENT_CONTACT : varchar(50)
		ESTABLISHMENT_CONTACT_TEL : varchar(20)
		ESTABLISHMENT_CONTACT_FAX : varchar(20)
		ESTABLISHMENT_CONTACT_EMAIL : varchar(50)
		LUNCH_TIME : datetime
		COMMENTS : varchar(2000)
		PROVISIONAL : bit
		ABBREVIATED_REQUIRED_MEMBERS : varchar(50)
		CONDUCTED : bit
		-- Audit --
		LAST_UPDATED_ON : datetime
		LAST_UPDATED_BY : int
		DELETED : datetime
	}

	class PANEL_PERIOD {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		START_DATE : datetime
		END_DATE : datetime
		-- Audit --
		DELETED : datetime
	}

	class PANEL_STATUS <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class PANEL_TYPE <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(50)
		ASSIGNABLE : int
		colour : varchar(50)
		MINREQUIRED : int
		ALLOW_MULTIPLE_PANELS : int
		PAPER_HEARING : bit
		SHOW_ON_WAM : int
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	class AUDIT_PANEL <<AuditTable>> {
		* ID : int
		-- Foreign Keys --
		* PANEL : int
		* CASEWORKER : int
		* RECORD_FIELD : int
		---
		ORIGINAL_VALUE : varchar(500)
		NEW_VALUE : varchar(500)
		-- Audit --
		* CHANGE_DATE : datetime
	}

	class AUDIT_PANEL_PERIOD <<AuditTable>> {
		* ID : int
		-- Foreign Keys --
		* PANEL_PERIOD_ID : int
		---
		* DESCRIPTION : varchar(50)
		START_DATE : datetime
		END_DATE : datetime
		-- Audit --
		CHANGE_BY : varchar(50)
		CHANGE_DATE : datetime
	}


	class RECORD_FIELD <<LookupTable>> {
		* ID : int
		---
		* DESCRIPTION : varchar(100)
		FIELD_NAME : : varchar(100)
		DETAIL : : varchar(2000)
		-- Visibility --
		SHOW_TO_UNIT : : int
		-- Audit --
		DELETED : : datetime
		LOV_DELETED_BY : : int
		LOV_UPDATED_BY : : int
		LOV_UPDATED_DATE : : datetime
		LOV_CREATED_BY : : int
		LOV_CREATED_DATE : : datetime
	}

	class RECORD_TYPE <<LookupTable>> {
		* ID : int
		---
		DESCRIPTION : varchar(50)
		-- Visibility --
		SHOW_TO_UNIT : int
		-- Audit --
		DELETED : datetime
		LOV_DELETED_BY : int
		LOV_UPDATED_BY : int
		LOV_UPDATED_DATE : datetime
		LOV_CREATED_BY : int
		LOV_CREATED_DATE : datetime
	}

	RECORD_FIELD }o--o| RECORD_TYPE


	class visit {
		panel : int
	}

	PANEL }o--|| PANEL_TYPE
	PANEL }o--|| PANEL_STATUS
	PANEL }o-u-o| moj.establishments.ESTABLISHMENT
	PANEL }o--o| visit
	PANEL }o--o| AUDIT_PANEL
	PANEL_PERIOD }o--o| AUDIT_PANEL_PERIOD

	AUDIT_PANEL }o--|| RECORD_FIELD
	AUDIT_PANEL }o-u-|| moj.caseworkers.CASEWORKER

	!include panel_members.puml
	!include member_fees.puml
	!include member_development.puml

}

@enduml
