@startuml
left to right direction
!include style_minimal.puml

!include common.puml
!include registers.puml
!include organisations.puml

!include application/index.puml

!include moj/index.puml
!include offenders/index.puml

!include documents/index.puml
!include notifications/index.puml

!include ppcs/index_parole.puml
' !include ppcs/index_panels.puml Can't be included at the same time as the line above, due to plantUML crashing
!include mhcs/index.puml
!include ppo/index.puml

!include reporting/index.puml

!include unknown.puml
@enduml
