@startuml

skinparam BackgroundColor #00000000

actor Caseworker
entity Service
boundary API
entity Migrator
database NewDB
database LegacyDB

group Migrate Data
  API -> LegacyDB : Query data
  API <[#green]- LegacyDB : Return results
  API -> NewDB : Store data for future use
end

== Initial Query ==

Caseworker -> Service : Use
Service -> API : GET data
API -> NewDB : Query data
API <[#red]- NewDB : No results
Service <[#green]- API : Return data
Caseworker <[#green]- Service : Display

== Subsequent Queries ==

Caseworker -> Service : Use
Service -> API : GET data
API -> NewDB : Query data
API <[#green]- NewDB : Return results
Service <[#green]- API : Return data
Caseworker <[#green]- Service : Display

== Writing Data ==

Caseworker -> Service : Use
Service -> API : PUT data
API -> NewDB : Update data
API <[#green]- NewDB : Success
Service <[#green]- API : Success
Caseworker <[#green]- Service : Confirm success

@enduml
