@startuml
!include ../style.puml

namespace application $MajorPackage {

	class LOGIN_LOG {
		* LOGIN_LOG_ID : int
		-- Foreign Keys --
		CASEWORKER_ID : int
		Application : int
		LOGIN_ACTION : int
		---
		LOGIN_NAME : varchar(100)
		* LOGIN_DATE : datetime
		* SUCCESS : bit
		IPAddress : varchar(50)
		browser : varchar(1000)
	}

	class GLOBAL_SETTINGS {
		* VARIABLE_NAME : varchar(50)
		-- Foreign Keys --
		APPLICATIONS : int
		---
		VARIABLE_VALUE : varchar(200)
		DESCRIPTION : varchar(2000)
		CATEGORY : varchar(100)
		-- Audit --
		LAST_UPDATED : datetime
		---
	}

	class UserSettings {
		* iUserSettingID : int
		-- Foreign Keys --
		* iUserID : int
		---
		* sDesc : varchar(255)
		* sValue : text
	}

	class ERROR_LOG {
		* ERROR_ID : int
		* CASEWORKER_ID : int
		ERROR_DATE : datetime
		MESSAGE : text
		SOURCE : varchar(255)
		FORM : varchar(255)
		QUERYSTRING : varchar(255)
		TARGETSITE : varchar(255)
		STACKTRACE : text
		DEALT_WITH : bit
	}


	class CONTEXT_SENSITIVE_HELP {
		* ID : int
		-- Foreign Keys --
		* HELP_PAGE_TYPE : int
		---
		* FORM_NAME : varchar(50)
		* TITLE : varchar(255)
		* HELP_TEXT : text
		* MAIN : bit
		* CHILD : bit
		* DPA : bit
		* SYSOPS : bit
		* LOGIN_TOP : bit
		* LOGIN_BOTTOM : bit
		* RECONFIRM : bit
		EXPIRED : datetime
	}


  !include aspnet.puml
  !include wam_users.puml
}

@enduml
